services:
  test_runner:
    build: .
    env_file:
      - .env
    networks:
      - skeleton_api
    restart: unless-stopped  # no = One execution only
    volumes:
      - ${PWD}/reports:/app/reports # Map host to container to extract report

networks:
  skeleton_api:
    external: true
